### ISSUE TITLE
 Default MaxPoolingOp only supports NHWC on device type CPU

### ISSUE THREAD

**Issue by JSOlier** [alexanderkroner/saliency#11]
Hi, 
I am trying to run the test function with the GPU, but I am getting this error:
"Default MaxPoolingOp only supports NHWC on device type CPU"
Everything works well when I use the CPU, though.

Best regards,

**Comment by alexanderkroner** [comment]
Hey, did you install `tensorflow-gpu`? With that package and the setting `"device": "gpu"` in the file `config.py` it should work fine.

**Comment by nealchecka** [comment]
Hi, I'm also seeing this issue. I installed with tensorflow-gpu and the setting is gpu in config.py.

**Comment by alexanderkroner** [comment]
Ok, I suspect that TensorFlow is not actually running on your GPU. You can check that via the commands:

- `assert tf.test.is_gpu_available()`
- `assert tf.test.is_built_with_cuda()`

If the assertions fail then you need to make sure that TensorFlow is correctly set up for GPU usage (https://www.tensorflow.org/install/gpu). Otherwise, you can just fall back to the CPU version.
