### ISSUE TITLE
Combining datasets for training

### ISSUE THREAD

**Issue by igkuz** [alexanderkroner/saliency#3]
First of all, thanks for the detailed solution, readable and reusable code using tensorflow.
Is it possible to combine all datasets and train network on all available data? 
I've read the README, and as far as I understood at first network must be trained on salicon, than executing train for the second time, it can fine tume the previous parameters for mit1003 or cat2000.

And is it possible to add to the list the dataset for webpages (dropbox: https://www.dropbox.com/s/30nxg2uwd1wpb80/webpage_dataset.zip?dl=0) mentioned here http://saliency.mit.edu/datasets.html (_Fixations in Webpage Images (FiWI) data set_)?

**Comment by alexanderkroner** [comment]
Hey, thank you for the kind words!

I added the FiWI dataset to the code and it can now be used with the argument `fiwi` like any of the other ones. This also includes a pre-trained model for testing.

Regarding the first part of your issue, it is true that currently the model needs to be trained on SALICON before it can be fine-tuned on any other dataset. This could be changed such that datasets are combined for a single training run instead of having one after another. I still need to check how this can be done but I will soon look into it!

**Comment by igkuz** [comment]
Thanks for you work!
